INSERT 
INTO  `s_kurz`
(
        `razeni`,
        `projekt_kod`,
        `kancelar_kod`,
        `kurz_druh`,
        `kurz_cislo`,
        `beh_cislo`,
        `kurz_lokace`,
        `kurz_zkratka`,
        `kurz_typ_kvalifikace`,
        `kurz_nazev`,
        `kurz_pracovni_cinnost`,
        `kurz_akreditace`,
        `kurz_obsah`,
        `pocet_hodin`,
        `pocet_hodin_distancne`,
        `certifikat_kurz_rada_FK`,
        `pocet_hodin_praxe`,
        `date_zacatek`,
        `date_konec`,
        `date_zaverecna_zkouska`,
        `dodavatel`,
        `info_cas_konani`,
        `info_misto_konani`,
        `info_lektor`,
        `harmonogram_filename`,
        `valid`
        ) 
     SELECT 

        IF(`s_kurz`.`id_s_kurz`,
            `s_kurz`.`id_s_kurz`,
            NULL) AS `id_s_kurz`,
        `s_kurz`.`razeni` AS `razeni`,
        `s_kurz`.`projekt_kod` AS `projekt_kod`,
        `s_kurz`.`kancelar_kod` AS `kancelar_kod`,
        IF(`s_kurz`.`kurz_druh`,
            `s_kurz`.`kurz_druh`,
            'RKJAZ') AS `kurz_druh`,
        `s_kurz`.`kurz_cislo` AS `kurz_cislo`,
        IF(`s_kurz`.`beh_cislo`,
            `s_kurz`.`beh_cislo`,
            1) AS `beh_cislo`,
        IF(`s_kurz`.`kurz_lokace`,
            `s_kurz`.`kurz_lokace`,
            `kurzy_zacatek_konec`.`lokace`) AS `kurz_lokace`,
        IF(`s_kurz`.`kurz_zkratka`,
            `s_kurz`.`kurz_zkratka`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'CJA1',
                'CJA2')) AS `kurz_zkratka`,
        IF(`s_kurz`.`kurz_typ_kvalifikace`,
            `s_kurz`.`kurz_typ_kvalifikace`,
            'čistá') AS `kurz_typ_kvalifikace`,
        IF(`s_kurz`.`kurz_nazev`,
            `s_kurz`.`kurz_nazev`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'Český jazyk pro cizince - základní kurz',
                'Český jazyk pro cizince - navazující kurz')) AS `kurz_nazev`,
        IF(`s_kurz`.`kurz_pracovni_cinnost`,
            `s_kurz`.`kurz_pracovni_cinnost`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'Český jazyk pro cizince - základní kurz',
                'Český jazyk pro cizince - navazující kurz')) AS `kurz_pracovni_cinnost`,
        IF(`s_kurz`.`kurz_akreditace`,
            `s_kurz`.`kurz_akreditace`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'Český jazyk pro cizince - základní kurz',
                'Český jazyk pro cizince - navazující kurz')) AS `kurz_akreditace`,
        `s_kurz`.`kurz_obsah` AS `kurz_obsah`,
        IF(`s_kurz`.`pocet_hodin`,
            `s_kurz`.`pocet_hodin`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                60,
                120)) AS `pocet_hodin`,
        IF(`s_kurz`.`pocet_hodin_distancne`,
            `s_kurz`.`pocet_hodin_distancne`,
            0) AS `pocet_hodin_distancne`,
        IF(`s_kurz`.`certifikat_kurz_rada_FK`,
            `s_kurz`.`certifikat_kurz_rada_FK`,
            'RK') AS `certifikat_kurz_rada_FK`,
        IF(`s_kurz`.`pocet_hodin_praxe`,
            `s_kurz`.`pocet_hodin_praxe`,
            0) AS `pocet_hodin_praxe`,
        IF(`s_kurz`.`date_zacatek`,
            `s_kurz`.`date_zacatek`,
            `kurzy_zacatek_konec`.`zacina`) AS `date_zacatek`,
        IF(`s_kurz`.`date_konec`,
            `s_kurz`.`date_konec`,
            `kurzy_zacatek_konec`.`konci`) AS `date_konec`,
        IF(`s_kurz`.`date_zaverecna_zkouska`,
            `s_kurz`.`date_zaverecna_zkouska`,
            `kurzy_zacatek_konec`.`konci`) AS `date_zaverecna_zkouska`,
        IF(`s_kurz`.`dodavatel`,
            `s_kurz`.`dodavatel`,
            'Grafia, s.r.o.') AS `dodavatel`,
        CONCAT(`kurzy_zacatek_konec`.`cas_vyuky`,
                ' | ',
                `kurzy_zacatek_konec`.`kdy`) AS `info_cas_konani`,
        `kurzy_zacatek_konec`.`kde` AS `info_misto_konani`,
        `kurzy_zacatek_konec`.`lektor` AS `info_lektor`,
        `s_kurz`.`harmonogram_filename` AS `harmonogram_filename`,
        IF(`s_kurz`.`valid`,
            `s_kurz`.`valid`,
            0) AS `valid`
    FROM
        (`kurzy_zacatek_konec`
        LEFT JOIN `s_kurz` ON ((`s_kurz`.`kurz_cislo` = `kurzy_zacatek_konec`.`kurz_c`)))
    WHERE
        (`s_kurz`.`projekt_kod` = 'CJC')