UPDATE  `s_kurz` AS s
INNER JOIN
(
    SELECT
        `s_kurz`.`id_s_kurz` AS `id_s_kurz`,
        `s_kurz`.`razeni` AS `razeni`,
        `s_kurz`.`projekt_kod` AS `projekt_kod`,
        IF(`s_kurz`.`kancelar_kod`  IS NOT NULL,
            `s_kurz`.`kancelar_kod`,
            CONCAT(`s_kurz`.`projekt_kod`,
                    '_',
                    IF(`s_kurz`.`kurz_lokace` IS NOT NULL,
                        `s_kurz`.`kurz_lokace`,
                        `kurzy_zacatek_konec`.`lokace`))) AS `kancelar_kod`,
        IF(`s_kurz`.`kurz_druh` IS NOT NULL,
            `s_kurz`.`kurz_druh`,
            'RKJAZ') AS `kurz_druh`,
        `s_kurz`.`kurz_cislo` AS `kurz_cislo`,
        IF(`s_kurz`.`beh_cislo` IS NOT NULL,
            `s_kurz`.`beh_cislo`,
            1) AS `beh_cislo`,
        IF(`s_kurz`.`kurz_lokace` IS NOT NULL,
            `s_kurz`.`kurz_lokace`,
            `kurzy_zacatek_konec`.`lokace`) AS `kurz_lokace`,
        IF(`s_kurz`.`kurz_zkratka` IS NOT NULL,
            `s_kurz`.`kurz_zkratka`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'CJA1',
                'CJA2')) AS `kurz_zkratka`,
        IF(`s_kurz`.`kurz_typ_kvalifikace` IS NOT NULL,
            `s_kurz`.`kurz_typ_kvalifikace`,
            'čistá') AS `kurz_typ_kvalifikace`,
        IF(`s_kurz`.`kurz_nazev` IS NOT NULL,
            `s_kurz`.`kurz_nazev`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'Český jazyk pro cizince - základní kurz',
                'Český jazyk pro cizince - navazující kurz')) AS `kurz_nazev`,
        IF(`s_kurz`.`kurz_pracovni_cinnost` IS NOT NULL,
            `s_kurz`.`kurz_pracovni_cinnost`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'Český jazyk pro cizince - základní kurz',
                'Český jazyk pro cizince - navazující kurz')) AS `kurz_pracovni_cinnost`,
        IF(`s_kurz`.`kurz_akreditace` IS NOT NULL,
            `s_kurz`.`kurz_akreditace`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                'Český jazyk pro cizince - základní kurz',
                'Český jazyk pro cizince - navazující kurz')) AS `kurz_akreditace`,
        `s_kurz`.`kurz_obsah` AS `kurz_obsah`,
        IF(`s_kurz`.`pocet_hodin` IS NOT NULL,
            `s_kurz`.`pocet_hodin`,
            IF((`kurzy_zacatek_konec`.`typ` = 'Z'),
                60,
                120)) AS `pocet_hodin`,
        IF(`s_kurz`.`pocet_hodin_distancne` IS NOT NULL IS NOT NULL,
            `s_kurz`.`pocet_hodin_distancne`,
            0) AS `pocet_hodin_distancne`,
        IF(`s_kurz`.`certifikat_kurz_rada_FK` IS NOT NULL,
            `s_kurz`.`certifikat_kurz_rada_FK`,
            'RK') AS `certifikat_kurz_rada_FK`,
        IF(`s_kurz`.`pocet_hodin_praxe` IS NOT NULL,
            `s_kurz`.`pocet_hodin_praxe`,
            0) AS `pocet_hodin_praxe`,
        IF(`s_kurz`.`date_zacatek` IS NOT NULL,
            `s_kurz`.`date_zacatek`,
            `kurzy_zacatek_konec`.`zacina`) AS `date_zacatek`,
        IF(`s_kurz`.`date_konec` IS NOT NULL,
            `s_kurz`.`date_konec`,
            `kurzy_zacatek_konec`.`konci`) AS `date_konec`,
        IF(`s_kurz`.`date_zaverecna_zkouska` IS NOT NULL,
            `s_kurz`.`date_zaverecna_zkouska`,
            `kurzy_zacatek_konec`.`konci`) AS `date_zaverecna_zkouska`,
        IF(`s_kurz`.`dodavatel` IS NOT NULL,
            `s_kurz`.`dodavatel`,
            'Grafia, s.r.o.') AS `dodavatel`,
        CONCAT(`kurzy_zacatek_konec`.`cas_vyuky`,
                ' | ',
                `kurzy_zacatek_konec`.`kdy`) AS `info_cas_konani`,
        `kurzy_zacatek_konec`.`kde` AS `info_misto_konani`,
        `kurzy_zacatek_konec`.`lektor` AS `info_lektor`,
        `s_kurz`.`harmonogram_filename` AS `harmonogram_filename`,
        IF(`s_kurz`.`valid` IS NOT NULL,
            `s_kurz`.`valid`,
            0) AS `valid`
    FROM
        (`kurzy_zacatek_konec`
        LEFT JOIN `s_kurz` ON ((`s_kurz`.`kurz_cislo` = `kurzy_zacatek_konec`.`kurz_c`)))
    WHERE
        (`s_kurz`.`projekt_kod` = 'CJC')) AS w ON s.`id_s_kurz`=w.`id_s_kurz`
SET
        s.`id_s_kurz`=w.`id_s_kurz`,
        s.`razeni`=w.`razeni`,
        s.`projekt_kod`=w.`projekt_kod`,
        s.`kancelar_kod`=w.`kancelar_kod`,
        s.`kurz_druh`=w.`kurz_druh`,
        s.`kurz_cislo`=w.`kurz_cislo`,
        s.`beh_cislo`=w.`beh_cislo`,
        s.`kurz_lokace`=w.`kurz_lokace`,
        s.`kurz_zkratka`=w.`kurz_zkratka`,
        s.`kurz_typ_kvalifikace`=w.`kurz_typ_kvalifikace`,
        s.`kurz_nazev`=w.`kurz_nazev`,
        s.`kurz_pracovni_cinnost`=w.`kurz_pracovni_cinnost`,
        s.`kurz_akreditace`=w.`kurz_akreditace`,
        s.`kurz_obsah`=w.`kurz_obsah`,
        s.`pocet_hodin`=w.`pocet_hodin`,
        s.`pocet_hodin_distancne`=w.`pocet_hodin_distancne`,
        s.`certifikat_kurz_rada_FK`=w.`certifikat_kurz_rada_FK`,
        s.`pocet_hodin_praxe`=w.`pocet_hodin_praxe`,
        s.`date_zacatek`=w.`date_zacatek`,
        s.`date_konec`=w.`date_konec`,
        s.`date_zaverecna_zkouska`=w.`date_zaverecna_zkouska`,
        s.`dodavatel`=w.`dodavatel`,
        s.`info_cas_konani`=w.`info_cas_konani`,
        s.`info_misto_konani`=w.`info_misto_konani`,
        s.`info_lektor`=w.`info_lektor`,
        s.`harmonogram_filename`=w.`harmonogram_filename`,
        s.`valid`=w.`valid`

